### ISSUE TITLE
Collect online forum data

### ISSUE THREAD

**Issue by theoaraujo** [uvacw/inca#121]
- Geenstijl.nl
- Fok.nl

**Comment by damian0604** [comment]
We will start with a health forum - this will be the Research Participation project of @Chamoetal . Which one is still to be determined, but we'll take one with a technique that is frequently used.

**Comment by damian0604** [comment]
This is solved by PR #245 (scraper voedingsforum). 
If specific other fora need to be scraped, the person/group needing them needs to take care of it.
