### ISSUE TITLE
Dutch regional newspapers (online version)

### ISSUE THREAD

**Issue by theoaraujo** [uvacw/inca#127]

**Comment by tamarafelicity** [comment]
Dagblad van het Noorden has a cookiewall that probably requires Selenium

**Comment by tamarafelicity** [comment]
De Stentor/AD has video articles like these: http://www.destentor.nl/binnenland/vanaf-5-mei-elke-dag-alles-over-de-giro-op-ad-nl~a625a32c/

Now these articles are just coded as videos ('is true')> more elaborated solution needed

**Comment by tamarafelicity** [comment]
Finalized regional papers.
