### ISSUE TITLE
Corporate Websites RSS

### ISSUE THREAD

**Issue by theoaraujo** [uvacw/inca#133]

**Comment by annekroon** [comment]
Yes! I would like to subscribing to the RSS feeds of - say - the 50 largest Dutch companies to keep track of all the news / press releases they send out. Potentially also scrape the Twitter accounts of these companies.

**Comment by theoaraujo** [comment]
@annekroon Did you already have a list of RSS feeds?

**Comment by annekroon** [comment]
[RSS feeds companies - national and international.xlsx](https://github.com/uvacw/inca/files/909316/RSS.feeds.companies.-.national.and.international.xlsx)

I got this: 10 international and 20 Dutch companies.  maybe we have to discuss @ program group whether this is still relevant or needs to be adjusted...(I think more is better)

**Comment by annekroon** [comment]
For the following companies we need scrapers

[companies_scrapersneeded.xlsx](https://github.com/uvacw/inca/files/1073858/companies_scrapersneeded.xlsx)
