### ISSUE TITLE
exception: can't convert from BSON type EOO to Date

### ISSUE THREAD

**Issue by arno12** [uvacw/inca#14]
http://stackoverflow.com/questions/28415995/exception-cant-convert-from-bson-type-eoo-to-date

**Comment by arno12** [comment]
Need to run following:

db.nlnieuws.find({datum: {$not: {$type: 9}}}).forEach(function(doc) {
    // Convert datum to a Date 
    doc.datum = new Date(doc.datum);
    db.nlnieuws.save(doc);
})

**Comment by damian0604** [comment]
is probably due to missing values. Partly fixed, but there are n=244 articles from 

> nos (www) 

left for which we have to find out 

> datum

**Comment by damian0604** [comment]
All articles have a date now, should be fixed.
