### ISSUE TITLE
Modify existing to also return image url and metadata

### ISSUE THREAD

**Issue by theoaraujo** [uvacw/inca#141]

**Comment by damian0604** [comment]
Image properties kreeg ik te pakken met deze snippet in lxml:

def _extract_images(dom_nodes):
images = []
for element in dom_nodes:
img = element.xpath('.//img')[0]
image = {
'url' : img.attrib['data-src'],
'height' : img.attrib['height'],
'width' : img.attrib['width'],
'alt' : img.attrib['alt'],
'caption' : _fon(element.xpath('.//p[@class="imageCaption"]/text()'))
}
images.append(image)
return images

Groet,

**Comment by damian0604** [comment]
see specificiations at 
[https://github.com/uvacw/inca/blob/development/doc/specifications.md](https://github.com/uvacw/inca/blob/development/doc/specifications.md)
