### ISSUE TITLE
Hash and store images from news scrapers

### ISSUE THREAD

**Issue by theoaraujo** [uvacw/inca#142]

**Comment by damian0604** [comment]
per discussion with @bobvdvelde , we can use 
https://github.com/JohannesBuchner/imagehash
together with storing the files on disk. i'll look into it

**Comment by bobvdvelde** [comment]
[The first answer here seems sensible](https://serverfault.com/questions/95444/storing-a-million-images-in-the-filesystem)

**Comment by damian0604** [comment]
- we'll make an image.py for all image-related processing
- we'll realize the downloading of images as a Processor (so that we can download the images at another moment then scrapng)

**Comment by damian0604** [comment]
Implemented by PR #192 (and earlier updates of news scrapers)
