### ISSUE TITLE
rss_scraper fails if parsehtml returns None

### ISSUE THREAD

**Issue by damian0604** [uvacw/inca#155]
scrapers that inherit from rss_scraper now exist with an error if parsehtml() returns None. This behavior is intended while testing (this really shouldn't happen), but for later (in production) we should change this in a way that it the scraper logs this error (better: alerts someone?), but keeps on scraping the pages itself, even if it fails at parsing.

**Comment by bobvdvelde** [comment]
I propose creating a custom exception called UnparsableException that emits a logger warning but is handled in the scraper loop. This will allow us to move to configurable SMTPHandler for logging later to enable email-based alerts on warnings (which is useful for remote instances).

**Comment by damian0604** [comment]
Good suggestion, thanks, @bobvdvelde ! I'll implement this once I find the time!
