### ISSUE TITLE
check if scrapers confirm to data model

### ISSUE THREAD

**Issue by damian0604** [uvacw/inca#161]
In particular, do they return a teaser if neccessary?

**Comment by bobvdvelde** [comment]
If I'm correct, this supposes the scraper is using an RSS feed that may or may not include a teaser text for news items. In this case, we may be able to base teaser inclusion on the [RSS specification](https://validator.w3.org/feed/docs/rss2.html) description. 

in pseudocode method of RSS scraper superclass:

```python
def rss_verify_teaser(item_raw, item_parsed):
    has_description = item_raw.get('description', False)
    has_teaser = item_parsed.get('teaser', False)
    if has_description and not has_teaser:
        raise("teaser is missing!")
```
Does that seem correct?

**Comment by damian0604** [comment]
Hi Bob,
We discovered that the teaser delivered by the RSS-feed is different from the teaser displayed on the page for several of the media (less common in NL, more common in other countries). We therefore decided to scrape both. 
See https://github.com/uvacw/inca/blob/development/doc/specifications.md

**Comment by bobvdvelde** [comment]
Makes sense. 

How does this relate to teasers on newspaper website homepages? As I understand it, there are three:
1. teaser as displayed when visiting the newspaper hompage (e.g. nrc.nl )
2. teaser that is in the RSS <description> element
3. teaser that is part of the article on the article page (e.g. nrc.nl/wilders%20zegt%20iets%20raars)
