### ISSUE TITLE
RSS parser does not address https 

### ISSUE THREAD

**Issue by dirtyjackeen** [uvacw/inca#162]
If the rss feed is https, then nothing is scraped e.g. 
`In [7]: feedparser.parse('https://www.rte.ie/news/rss/news.xml')`
`Out[7]: 
{'bozo': 1,
 'bozo_exception': urllib.error.URLError(ssl.SSLError(1,
                                    '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)')),
 'entries': [],
 'feed': {}}`

**Comment by bobvdvelde** [comment]
Are there situations were using the non-https endpoint is not a valid workaround? 

e.g. 'http://www.rte.ie/news/rss/news.xml' instead of 'https://www.rte.ie/news/rss/news.xml'

**Comment by bobvdvelde** [comment]
Alternatively, a fallback option would be to use `requests` to obtain the feed content and feed the resulting string to `feedparser.parse`

```python
import feedparser
import requests

is_https = "https://" in feed_url[:len("https://")]
if not is_https:
  feed_content = requests.get(feed_url)
  feed = feedparser.parse(feed_content.text)
elif is_https:
  feed = feedparser.parse(feed_url)

print(feed)
```

Could you elaborate on the situation in which this is a problem?

**Comment by dirtyjackeen** [comment]
Using the non-https end works for RTE actually, thanks. I will try it with a few others and see if helps.

**Comment by bobvdvelde** [comment]
I will mark this issue as closed pending further run-ins with this problem.

**Comment by dirtyjackeen** [comment]
Unfortunately, I have encountered this issue again trying to scrape Vice and it's subpages (like Motherboard). I have looked into a few solutions, such as removing the 's', using the code above, and trying `verify=False` in the request. No luck so far. Any suggestions?

**Comment by bobvdvelde** [comment]
Could you post a minimal example? That would help me reproduce & debug!

**Comment by dirtyjackeen** [comment]
Apologies for the slow reply, was on holidays. For example, when using this:
```
class vice(rss):
    """Scrapes vice.com/nl"""

    def __init__(self,database=True,verify=False):
        self.database=database
        self.doctype = "vice (www)"
        self.rss_url= "https://www.vice.com/nl/rss"
        self.version = ".1"
        self.date    = datetime.datetime(year=2017, month=7, day=2)
```

No pages are downloaded.

**Comment by bobvdvelde** [comment]
Could you provide code that I can run? Or perhaps indicate which branch this version of the vice rss scraper is in?

e.g. something like: 

```python
from inca import Inca
client = Inca()
docs = client.scrapers.vice()
```

Thanks!

**Comment by dirtyjackeen** [comment]
Just spent a good amount of time trying to fix the problem, and I think the issue is actually due to a cookie wall (in the case of Vice anyway). I'll start looking at ways around it!

**Comment by bobvdvelde** [comment]
That might mean you have to use a requests session instead of a direct request. 

```python
import requests
session = requests.Session()
session.get('http://example.org')
session.get('http://example.org/YouNeedACookie') # cookie from first request persists
```

Again, I'm happy to help, but please put in a small example to reproduce the problem that can be copy-pasted into an interpreter.

**Comment by dirtyjackeen** [comment]
Ok. Sorry I am still quite new to this. I have been writing the scraper scripts in Brackets eg:
```
import datetime
from lxml.html import fromstring
from core.scraper_class import Scraper
from scrapers.rss_scraper import rss
from core.database import check_exists
import feedparser
import re
import logging
import requests

logger = logging.getLogger(__name__)

def polish(textstring):
    #This function polishes the full text of the articles - it separated the lead from the rest by ||| and separates paragraphs and subtitles by ||.
    lines = textstring.strip().split('\n')
    lead = lines[0].strip()
    rest = '||'.join( [l.strip() for l in lines[1:] if l.strip()] )
    if rest: result = lead + ' ||| ' + rest
    else: result = lead
    return result.strip()

class vice(rss):
    """Scrapes vice.com/nl"""

    def __init__(self,database=True):
        self.database=database
        self.doctype = "vice (www)"
        self.rss_url= "https://www.vice.com/nl/rss"
        self.version = ".1"
        self.date    = datetime.datetime(year=2017, month=7, day=25)

    def parsehtml(self,htmlsource):
        '''
        Parses the html source to retrieve info that is not in the RSS-keys
        In particular, it extracts the following keys (which should be available in most online news:
        section    sth. like economy, sports, ...
        text        the plain text of the article
        byline      the author, e.g. "Bob Smith"
        byline_source   sth like ANP
        '''
    
        try:
            tree = fromstring(htmlsource)
        except:
            print("cannot parse?",type(doc),len(doc))
            print(doc)
            return("","","", "")

        try:
            title = tree.xpath("//*[@class='article__title']//text()")
        except:
            title = ""
            logger.info("No 'title' field encountered - don't worry, maybe it just doesn't exist.")
```
and then testing them in Terminal. Because of the cookie wall, I have been getting this:
```
In [1]: import inca
WARNING:core.import_class:No MongoDB support
WARNING:processing.basic_text_processing:Pattern is NOT python 3 compatible...skipping

In [2]: r=inca.scrapers.vice_scraper.vice(database=False)

In [3]: q=r.run()

In [4]: len(q)
Out[4]: 0
```

**Comment by dirtyjackeen** [comment]
I managed to resolve the issue for two of the https sites (Geenstijl and Buzzfeed). It had to do with the fact that Python 3.6 on MacOS uses an embedded version of OpenSSL. The problem remains with Vice and it's subs though.

**Comment by bobvdvelde** [comment]
It seems Vice employs a cookie-wall even for the generall RSS feed, which means that the feedparser doesn't work...

```python
import feedparser
feed = feedparser.parse("https://www.vice.com/nl/rss")
print("entries : {feed[entries]}, exception : {feed[bozo_exception]}".format(**locals()))
> entries : [], exception : <unknown>:32:40: not well-formed (invalid token)
```

You can see the problem when you try and get the url directly

```python
import requests
res = requests.get('https://www.vice.com/nl/rss')
print(res.text)
> <lot's of stuff that does not look like XML>
```
Basically, it's the thing you see if you would go to https://www.vice.com/nl/rss in an incognito tab of your browser.

So, we need a workaround for the cookiewall. After some sleuthing with the Chrome debugger, it turns out that going through the cookiewall page sets a cookie (using Javascript, _ze bastards_). This means you can work around the issue as such:

```python
import requests
import feedparser

session = requests.Session()
session.cookies['cookiewall'] = 'yes'
feedpage = session.get('https://www.vice.com/nl/rss')
feed = feedparser.parse(feedpage.text)
print("entries : {feed[entries]}".format(**locals()))
```
You will need to implement this solution in the `.get` method of your scraper instead of relying on the superclass method in `rss`. Hope that helps!

**Comment by dirtyjackeen** [comment]
Fantastic! Thanks Bob! Will try that now.
