### ISSUE TITLE
Generic RSS scraper compatibility with https 

### ISSUE THREAD

**Issue by bobvdvelde** [uvacw/inca#163]
Feedparser seems to be brittle in the face of https based endpoints. The generic rss scraper should be made more robust to handle https based feeds. The below snippet is probably what needs to be added. 

```python
import feedparser
import requests

is_https = "https://" in feed_url[:len("https://")]
if is_https:
  feed_content = requests.get(feed_url)
  feed = feedparser.parse(feed_content.text)
elif not is_https:
  feed = feedparser.parse(feed_url)

print(feed)
```

**Comment by damian0604** [comment]
As a side effect of PR #208 , this is solved.
