### ISSUE TITLE
time-series analysis support

### ISSUE THREAD

**Issue by theoaraujo** [uvacw/inca#170]
Bob to include details

**Comment by bobvdvelde** [comment]
Should include:
- assumption checks
- on failure fallback to appropriate method (if possible & unless overridden by user) 
- basic explanation of results, including assumption check results
- result plots
- diagnostic plots
- interpretation

**Comment by bobvdvelde** [comment]
Maksim will work on this now!

**Comment by damian0604** [comment]
see PR #308
