### ISSUE TITLE
add top UK newspapers / online

### ISSUE THREAD

**Issue by theoaraujo** [uvacw/inca#172]

**Comment by annekroon** [comment]
Scrapers for the following news sites: 

-	The Sun
-	Daily Mail
-	Daily Telegraph
-	The Independent
-	The Guardian

**Comment by dirtyjackeen** [comment]
No Sun RSS feed. Daily Star (not listed) is complete.

**Comment by dirtyjackeen** [comment]
Daily Star pull request made. Will work on The Sun now.

**Comment by dirtyjackeen** [comment]
The Sun was pulled on Friday. Will work on the Daily Telegraph now.

**Comment by dirtyjackeen** [comment]
Telegraph pull req made. Will work on The Independent next.

**Comment by dirtyjackeen** [comment]
Independent and The Guardian pull reqs made. Slight issue with the Guardian. Could only get the UK News (https://www.theguardian.com/uk-news/rss) rss feed to work. The main feeds (i.e. https://www.theguardian.com/uk/rss and https://www.theguardian.com/international/rss) don't seem to work with our `rss_scraper`

**Comment by dirtyjackeen** [comment]
All UK scrapers (listed) complete.
