### ISSUE TITLE
Error in client.database.doctype

### ISSUE THREAD

**Issue by theoaraujo** [uvacw/inca#178]
<ipython-input-11-05a815064cfb> in <module>()
----> 1 client.database.doctype_inspect('tweet')

.../inca17/inca_api/core/search_utils.py in doctype_inspect(doctype)
    145     summary = dict(
    146         total_collected=0,
--> 147         first_collected=datetime(),
    148         last_collected=datetime(),
    149         keys=doctype_fields(doctype)

**Comment by bobvdvelde** [comment]
There is now a fix available in pull request #179 

Please review and close this issue if accepted

**Comment by bobvdvelde** [comment]
closed as #179 was accepted
