### ISSUE TITLE
Pymongo usersubset invalid - Value error

### ISSUE THREAD

**Issue by arno12** [uvacw/inca#2]
> ValueError: malformed node or string: {'$or': [{'source': 'nrc (www)'}, {'source': 'volkskrant (www)'}, {'source': 'fok'}, {'source': 'fok'}], 'datum': {'$gte': datetime.datetime(2013, 1, 2, 0, 0), '$lte': datetime.datetime(2014, 3, 4, 0, 0)}} 
>       args = ("malformed node or string: {'$or': [{'source': 'n...0), '$lte': datetime.datetime(2014, 3, 4, 0, 0)}}",) 
>       with_traceback = <built-in method with_traceback of ValueError object>

`all=collection.find(ast.literal_eval(usersubset),{"text": 1, "_id":0})`
might be the problematic bit, not sure it's extracting info from dict as it should.

**Comment by arno12** [comment]
Ok so clearly the issue is linked to the "ast.literal_eval()" which cannot evaluate the dict that is issued as a subset. 
Simply in Python,
`import ast
subset = {'$or': [{'source': 'nrc (www)'}, {'source': 'volkskrant (www)'}]}
cleaned = ast.literal_eval(subset)`

> ValueError: malformed node or string: {'$or': [{'source': 'nrc (www)'}, {'source': 'volkskrant (www)'}]}

Tried to read up on the documentation of ast.literal_eval but I'm stuck. 

Note: tried to run `all=collection.find(usersubset,{"text": 1, "_id":0})`
in which case it will run continuously and return a 500 error

**Comment by damian0604** [comment]
ast.literal_eval expects a string as input. Therefore,
`ast.literal_eval({'$or': [{'source': 'nrc (www)'}, {'source': 'volkskrant (www)'}, {'source': 'fok'}, {'source': 'fok'}]})`
produces as error, while
`ast.literal_eval("{'$or': [{'source': 'nrc (www)'}, {'source': 'volkskrant (www)'}, {'source': 'fok'}, {'source': 'fok'}]}")`
works as expected:
`In [13]: ast.literal_eval("{'$or': [{'source': 'nrc (www)'}, {'source': 'volkskrant (www)'}, {'source': 'fok'}, {'source': 'fok'}]}")
Out[13]: 
{'$or': [{'source': 'nrc (www)'},
  {'source': 'volkskrant (www)'},
  {'source': 'fok'},
  {'source': 'fok'}]}
`

Does this solve this?

**Comment by arno12** [comment]
Yes, will update now
