### ISSUE TITLE
Date error: 1940

### ISSUE THREAD

**Issue by arno12** [uvacw/inca#22]
Some articles, or at least this one:

{ "_id" : ObjectId("56a104d12d00592736a1700a"), "title" : " De lastige herinnering aan een verloren slag", "datum" : ISODate("1940-05-12T00:00:00Z"), "source" : "trouw (print)", "length_words" : 1945, "addedbydate" : ISODate("2016-01-21T17:18:25.762Z"), "addedby" : "datamanager 0.11", "byline" : "QUIRIJN VISSCHER", "addedbyuser" : "anne", "length_char" : 12282, "text" : " Het is 75...

**Comment by damian0604** [comment]
I looked the correct date up on LexisNexis and replaced it. Should be ok now:
```
> db.nlnieuws.find({"datum":  {$lt:ISODate("1990-01-01T00:00:00.00Z")  }}).count()
0

```
