### ISSUE TITLE
make verify.py more robust

### ISSUE THREAD

**Issue by damian0604** [uvacw/inca#24]
- add `.batch_size(5)` or similar to `find` to avoid timeouts 
- check if sth has been annotated already and do not ask to code this again (so that user can resume annotating where he was automatically)

**Comment by Joannastr** [comment]
I have added a function that checks if the article already has the key True. Only if it is not, it needs to be coded. This should be a quick solution to this.

**Comment by damian0604** [comment]
This refers to the legacy version of inca based on MongoDB, if we want a similar function, it needs to be reimplemented anyway. Closing it for now.
