### ISSUE TITLE
export_doctype uses invalid file names

### ISSUE THREAD

**Issue by damian0604** [uvacw/inca#254]
`export_doctype` calls the documents ``id`.json`; however, ids can contain invalid characters like slashes.
Possible solution: hash the ids.

`import hashlib` and use something like `'{}.json'.format(hashlib.sha224(doc['_id'].encode('utf-8')).hexdigest())` as file name

**Comment by bobvdvelde** [comment]
But hashes are asymmetric, meaning that the filenames will become unintelligible. Perhaps a symmetric, 'path-safe' transformation should be applied? I'll give it a whirl once I implement the basics for exporting.

**Comment by damian0604** [comment]
Good point. Maybe we can use url encoding?
like this:
```
In [10]: import urllib
In [11]: urllib.parse.quote_plus('//')
Out[11]: '%2F%2F'
```

**Comment by damian0604** [comment]
I'm just going to pick this up and to use URL quoting, will issue an PR later today
