### ISSUE TITLE
doctypes of rss scrapers

### ISSUE THREAD

**Issue by FeLoe** [uvacw/inca#327]
When trying to search for all outlets in the rssscrapers automatically in the database, I discovered that there are some issues with naming the doctypes of the rss scrapers: 
- the ing scraper gets the doctype "nu"
- the elpais scraper gets the doctype "abc"
- for the newspapers "Neues Deutschland", "Zeit", "Junge Welt" the url is the doctype

We also have the dailymail and the walmart scraper twice and the class "independent" exists twice (same name for irish and uk version) and various other scrapers are not named consistently (only adding "(corp)" or "(www)" to the class name to get the document name) such as "Die Welt".

These issues make it very difficult to search for these doctypes in the database (at least in an automated way..) - should they be renamed? This would then also require to think about what to do with all the already scraped documents from these doctypes.

**Comment by FeLoe** [comment]
here are all the classes/doctypes that do not match the usual pattern (class as key, doctype as value): 
{"ree": "Red Electrica Corp (corp)", "bbva":"BBVA (corp)", "popular": "Banco Popular (corp)", "gnf":"GNF (corp)","thetelegraph": "telegraph (www)", "freitag":"Der Freitag", "independent":["independent-uk (www)", "independent-irl (www)"], "jungefreiheit":"Junge Freiheit", "hetbelangvanlimburg":"belangvanlimburg (www)", "neues":"https://www.neues-deutschland.de", "zeit":"http://zeit.de", "jungewelt":"https://www.jungewelt.de", "taz":"die tageszeitung", "boskalispress":"boskalis press (corp)", "diageonews":"diageo (corp)", "handelsblatt":"Handelsblatt", "tagesspiegel":"DerTagesspiegel", "diewelt":"Die Welt","elpais": "abc (www)", "bbcni":"BBC Northern Ireland (www)", "metronieuws":"metro (www)", "nu":"ing"}

**Comment by damian0604** [comment]
Thanks for flagging this!!

**Comment by damian0604** [comment]
@Joannastr can you change this while working on the docstrings (as you are working on the scraper files anyway)?
@FeLoe let's think together about a way of fixing this for data in the past...

**Comment by Joannastr** [comment]
Fixed for all rss scrapers
