### ISSUE TITLE
Make database=True for scrapers part of .run()/.runwrap() instead of __init__

### ISSUE THREAD

**Issue by damian0604** [uvacw/inca#357]
Because the preferred way of using inca is via an instance of the Inca-class, and because of the way how the Celery tasks are constructed, it is essentially impossible to use the database=False argument (unless one keeps using inca directly, bypassing the preferred way of working).

**Comment by damian0604** [comment]
indeed, same thing!

**Comment by FeLoe** [comment]
new commit now also includes the other arguments in .run()
