### ISSUE TITLE
Junk news aggregator

### ISSUE THREAD

**Issue by Judithmoeller** [uvacw/inca#446]
The Oxford Internet Institute developed a Junk  news aggregator that aggregates news from  questionable sources along with popularity metrics on social media: https://newsaggregator.oii.ox.ac.uk/news/app/

I have a couple of project ideas based on that but they all start with a scraper - I would be willing to write it but would need serious support.

**Comment by laurasav** [comment]
Hi @Judithmoeller I'd like to help with that! I am working for the project until the end of December. We could meet up and discuss the scraper :)

**Comment by Judithmoeller** [comment]
Hoi @laurasav . I have not figured out how to send you a direct message, but if you can: let's find a time to meet. You can also just send me an email :-)
