### ISSUE TITLE
German newspaper Süddeutsche Zeitung 

### ISSUE THREAD

**Issue by bobvdvelde** [uvacw/inca#62]
Süddeutsche Zeitung can be found at http://www.sueddeutsche.de/

**Comment by arno12** [comment]
I have a general question about the RSS feeds. 
Most of the time, newspapers offer feeds by category or a general feed. I usually opt for the general one. Do I need to iterate over every feed and exclude articles that are duplicates? If so should I do so based on URL?

Secondly, most of those feeds are limited to the very latest articles (e.g. http://rss.sueddeutsche.de/rss/Topthemen) only offers about 30 articles. How do we deal with this?

**Comment by bobvdvelde** [comment]
Hi Arno, 

The preference is the general RSS feed. If you use the article URL as the identity of the item, duplicates will automatically be avoided in ES. 

The thing with RSS feeds is that they are nice for ongoing data collection, but not historical data collection. We deal with this by running the RSS feeds every hour, and avoid relying on the RSS feed for projects were we need more historical data.

**Comment by arno12** [comment]
There is a challenge to retrieve all pages of the article in one. This website doesn't offer a full-url. It uses javascript. So we have 

< a class="article-paging-nav-btn--small" onclick="document.getElementById('singlePageForm').submit(); return false;">click < /a>

I suppose that the best would be to use some Jquery when we call the page url and try to do something like

> try: $('.singlePageForm').show()

But we would need Pyquery? I've never used it personally but I recommend we add it for these cases where a responsive website needs to javascript to retrieve parts of the articles. For now, I will manually check whether there are (up to 4) pages.

**Comment by bobvdvelde** [comment]
Hi Arno, 

I believe the most elegant solution would be to use Selenium. You can find an example for python here: https://realpython.com/blog/python/headless-selenium-testing-with-python-and-phantomjs/ .
