### ISSUE TITLE
German newspaper: Frankfurter Allgemeine Zeitung

### ISSUE THREAD

**Issue by bobvdvelde** [uvacw/inca#63]
Frankfurter Allgemeine Zeitung can be found at http://www.faz.net/

**Comment by arno12** [comment]
1. Faz PLUS, e.g., http://plus.faz.net/evr-editions/2016-12-13/41128/300082.html can be added once we find a way to go through paywalls (#52) 
2. Many articles simply don't have authors (specific editorial policy to insure anonymity?)

**Comment by Jaerli** [comment]
The scraper is written but the syntax scraping the text is not good yet. i cannot not further adjust it at this moment. it includes things like pop ups asking to install another web browser.

**Comment by Jaerli** [comment]
The scraper is written but the text is still returning the text of pop ups from the pages and other stuff. after i ve pushed it it would be good if someone else had a look at it. everything else works fine.

**Comment by damian0604** [comment]
@Jaerli I cannot find it? Maybe you didn't push it yet?

**Comment by FeLoe** [comment]
The scraper is finished now and merged into development
