### ISSUE TITLE
German newspaper: Junge Freiheit

### ISSUE THREAD

**Issue by bobvdvelde** [uvacw/inca#71]
Junge Freiheit can be found at https://jungefreiheit.de/

**Comment by Jaerli** [comment]
i wrote the scraper to this newspaper. But i ran into one problem. the teaser can only be seen when looking at an overview of the articles. once clicked on the article, the teaser is not detectable anymore. but in any case the teaser is a part of the text, but not always the same part. is there anyway i can scrape the teaser from another page than the rest?

**Comment by FeLoe** [comment]
The scraper is now merged into development. Still no teaser, but we have the RSS teaser as alternative.
